### PR TITLE
Allow to sync just one directory in the root

### PR DESCRIPTION
**Pull request by vitalif**
Hi! This patch allows a simple kind of partial sync - it allows to sync only one root subdirectory of the google drive.

### CODE REVIEW

**Comment by shumushin** [comment]
Hey, any chance that this will be committed? Using Google Drive to backup my server and do not want it to sync my photos to the server for no reason :)

Thanks!

**Comment by mennanov** [comment]
Is it going to be merged into master?

Looking forward!

**Comment by vitalif** [comment]
Wow! Nice to see you)))). I'm maintaining grive2. I've asked you to hand over the original repo by email, not sure if it arrived...

**Comment by nestal** [comment]
Sorry I missed it. I have added you to the team.

Thanks for taking it over.

**Pull request merged**
